name: Super-Linter

on: push
env:
 SONAR_PROJECT_KEY : Samron10_Project
 SONAR_ORGANIZATION : Samron10
 SONAR_TOKEN : 0f6cdf1ca861312a82086449c3fdc8fc48046c9c
    
jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          projectKey: ${{ env.SONAR_PROJECT_KEY }}
          organization: ${{ env.SONAR_ORGANIZATION }}
          token: ${{ env.SONAR_TOKEN }}    

     
